# Generated by Django 6.0.1 on 2026-01-13 14:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_ref',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_reference',
            field=models.CharField(default='MIGRATION_FIX', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='transactions.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 28, 14, 20, 18, 487106, tzinfo=datetime.timezone.utc)),
        ),
    ]
