# Generated by Django 6.0.1 on 2026-01-13 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_payment_payment_ref_payment_payment_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 28, 14, 22, 2, 457, tzinfo=datetime.timezone.utc)),
        ),
    ]
